vector_search_endpoint_name: "one-env-shared-endpoint-5"
vector_search_index: "jendarra_cat.pragster.gold_pragster_pdfs_chunked_index"
# These must be set to use the Review App
vector_search_schema:
  primary_key: chunk_id
  chunk_text: chunked_text
  document_source: doc_uri
vector_search_parameters:
  k: 3
chunk_template: "`{chunk_text}`\n"
chat_endpoint: "databricks-dbrx-instruct"
chat_prompt_template: "You are a trusted assistant that helps answer questions about Databricks partners. Here is some context which might or might not help you answer questions about Databricks partners: {context}. If a user asks about a specific company, and you have no context about a company of that name, then just say that you are not aware of a company of that name and do not mention other partner companies. If a user asks whether you know any partners who meet the user's criteria, list the partners that may be relevant to them, with a blurb about each. Answer directly, do not repeat the question, do not start with something like: the answer to the question, do not add AI in front of your answer, do not say: here is the answer, do not mention the context or the question. Based on this history and context, answer this question: {question}."
chat_prompt_template_variables:
  - "context"
  - "question"
chat_endpoint_parameters:
  temperature: 0.01
  max_tokens: 500